---

- debug:
    msg:
      - '################################################################################'
      - '################################################################################'
      - '############################# Preparing for Update #############################'
      - '################################################################################'
      - '################################################################################'

- name: GA | Update | Prep | Validating repo
  ansible.builtin.import_tasks: prep/repo_valid.yml

- name: GA | Update | Prep | Version handling
  ansible.builtin.import_tasks: prep/version.yml
