---

- name: GA | Update | Prep | Version | After-Git | Get commit version
  ansible.builtin.shell: "cd {{ ga_update_path_repo }} && git log -1 | grep commit | cut -d ' ' -f2"
  changed_when: false
  register: ga_raw_commit
  when: ga_update_type == 'release'

- name: GA | Update | Prep | Version | After-Git | Setting commit version
  ansible.builtin.set_fact:
    ga_update_commit_new: "{{ ga_raw_commit.stdout[:8] }}"
  changed_when: false
  when: ga_update_type == 'release'

- name: GA | Update | Prep | Version | After-Git | Release
  ansible.builtin.import_tasks: prep/version_release.yml
  when: ga_update_type == 'commit'
