---

- name: GA | Cert LetsEncrypt | Dependencies | Deploying temporary apache site
  ansible.builtin.template:
    src: 'templates/etc/apache2/sites-available/lets_encrypt.conf.j2'
    dest: "/etc/apache2/sites-available/tmp_lets_encrypt.conf"
    owner: 'root'
    group: 'root'
    mode: 0644
  ignore_errors: yes
  register: tmp_site_config

- name: GA | Cert LetsEncrypt | Dependencies | Enable apache site
  ansible.builtin.file:
    state: link
    src: "/etc/apache2/sites-available/tmp_lets_encrypt.conf"
    dest: "/etc/apache2/sites-enabled/tmp_lets_encrypt.conf"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: GA | Cert LetsEncrypt | Dependencies | Reload apache
  ansible.builtin.systemd:
    name: 'apache2.service'
    state: reloaded
