---

- name: GA | Devices | Installing packages
  apt:
    name: "{{ ga_device_packages }}"
    state: present

- name: GA | Devices | Install python modules into venv
  pip:
    name: "{{ ga_device_mods }}"
    virtualenv: "{{ ga_core_path_venv }}"
    virtualenv_python: "{{ ga_python_version }}"
    state: present

- name: GA | Core | Copying device-code
  shell: "cp -r {{ setup_clone_dir }}/code/device {{ ga_core_path }} &&
  chown -R {{ ga_core_service_user }}:{{ ga_service_group }} {{ ga_core_path }}/device &&
  chmod 775 -R {{ ga_core_path }}/device"

- name: GA | Devices | Adding service user to groups
  user:
    name: "{{ ga_core_service_user }}"
    groups: "{{ ga_device_groups }}"
    append: yes

- name: GA | Devices | Configuring raspi-config
  shell: "raspi-config {{ item }}"
  with_items: "{{ ga_device_raspiconfig }}"
  ignore_errors: true
