---

- name: GA | Devices | Installing packages
  ansible.builtin.apt:
    name: "{{ ga_device_packages }}"
    state: present

- name: GA | Devices | Install python modules into venv
  ansible.builtin.pip:
    name: "{{ ga_device_mods }}"
    virtualenv: "{{ ga_core_path_venv }}"
    virtualenv_python: "python{{ ga_python_version }}"
    virtualenv_command: '/usr/bin/virtualenv'
    executable: pip3
    state: present

- name: GA | Core | Copying device-code
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/device"
    dest: "{{ ga_core_path }}/"
    recursive: yes
    rsync_path: 'sudo rsync'
    rsync_opts: ['--exclude=__pycache__/']

- name: GA | Core | Setting privileges for device scripts
  ansible.builtin.file:
    path: "{{ ga_core_path }}/device"
    state: directory
    owner: "{{ ga_core_service_user }}"
    group: "{{ ga_service_group }}"
    recurse: true
    mode: 0770

- name: GA | Devices | Adding service user to groups
  ansible.builtin.user:
    name: "{{ ga_core_service_user }}"
    groups: "{{ ga_device_groups }}"
    append: yes

- name: GA | Devices | Configuring raspi-config
  ansible.builtin.command: "raspi-config {{ item }}"
  loop: "{{ ga_core_raspiconfig }}"
  ignore_errors: true
