---

- name: GA | Core | Update | Creating directory
  ansible.builtin.file:
    path: "{{ ga_update_path }}"
    state: directory
    owner: "{{ ga_update_service_user }}"
    group: "{{ ga_update_service_user }}"
    mode: 0755

- name: GA | Core | Update | Adding update service file
  ansible.builtin.template:
    src: 'templates/lib/systemd/system/ga_update.service.j2'
    dest: '/lib/systemd/system/ga_update.service'

- name: GA | Core | Update | Copying update-code
  ansible.builtin.shell: "cp -r {{ setup_clone_dir }}/code/update/* {{ ga_update_path }} &&
  chown -R {{ ga_update_service_user }}:{{ ga_update_service_user }} {{ ga_update_path }} &&
  chmod -R 750 {{ ga_update_path }}"

- name: GA | Core | Update | Adding service user
  ansible.builtin.user:
    name: "{{ ga_update_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "/home/{{ ga_update_service_user }}"

- name: GA | Core | Update | Adding privileges
  ansible.builtin.template:
    src: 'templates/etc/sudoers.d/gaupdate.j2'
    dest: '/etc/sudoers.d/gaupdate'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
