---

- name: GA | Core | Update | Adding service user
  ansible.builtin.user:
    name: "{{ ga_update_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "{{ ga_update_path_home }}"
    groups: "{{ ga_service_group }}"
    append: yes

- name: GA | Core | Update | Creating directory
  ansible.builtin.file:
    path: "{{ ga_update_path }}"
    state: directory
    owner: "{{ ga_update_service_user }}"
    group: "{{ ga_update_service_user }}"
    mode: 0755

- name: GA | Core | Update | Adding update service file
  ansible.builtin.template:
    src: 'templates/lib/systemd/system/ga_update.service.j2'
    dest: "/lib/systemd/system/{{ ga_update_service }}"

- name: GA | Core | Update | Copying update-code
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/update/"
    dest: "{{ ga_update_path }}/"
    recursive: yes
    rsync_path: 'sudo rsync'
    rsync_opts: ['--exclude=*.cnf', '--exclude=*.key', '--exclude=__pycache__/']
    dest_port: "{{ ansible_port | default(ga_ssh.port) }}"

- name: GA | Core | Update | Setting privileges
  ansible.builtin.file:
    path: "{{ ga_update_path }}"
    state: directory
    owner: "{{ ga_update_service_user }}"
    group: "{{ ga_update_service_user }}"
    recurse: true
    mode: 0750

- name: GA | Core | Update | Adding service user
  ansible.builtin.user:
    name: "{{ ga_update_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "{{ ga_update_path_home }}"

- name: GA | Core | Update | Adding privileges
  ansible.builtin.template:
    src: 'templates/etc/sudoers.d/gaupdate.j2'
    dest: '/etc/sudoers.d/gaupdate'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
