---

- name: GA | Web | Installing packages
  ansible.builtin.apt:
    name: "{{ ga_web_packages }}"
    state: present

- name: GA | Web | Setting system timezone
  community.general.timezone:
    name: "{{ ga_timezone }}"

- name: GA | Web | Adding service group
  ansible.builtin.group:
    name: "{{ ga_service_group }}"
    state: present

- name: GA | Web | Adding service user
  ansible.builtin.user:
    name: "{{ ga_web_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "{{ ga_web_path_home }}"
    groups: "{{ ga_web_groups }}"
    append: yes

- name: GA | Web | Creating directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ga_web_service_user }}"
    group: "{{ ga_service_group }}"
    mode: 0755
  loop:
    - "{{ ga_web_path }}"
    - "{{ ga_web_path_log }}"
    - "{{ ga_web_path_static }}"
    - "{{ ga_web_path_venv }}"

- name: GA | Web | Copying web code
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/web/{{ ga_web_django_project }}/"
    dest: "{{ ga_web_path }}"
    recursive: yes
    rsync_path: 'sudo rsync'
    rsync_opts:
      - '--exclude=*.cnf'
      - '--exclude=*.conf'
      - '--exclude=static/'

- name: GA | Web | Copying web static-files
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/web/{{ ga_web_django_project }}/static/"
    dest: "{{ ga_web_path_static }}"
    recursive: yes
    rsync_path: 'sudo rsync'

- name: GA | Web | Configuring django settings
  ansible.builtin.lineinfile:
    path: "{{ ga_web_path }}/{{ ga_web_django_project }}/config.py"
    regexp: '{{ item.search }}'
    line: '{{ item.replace }}'
  loop: "{{ ga_django_config_replacement }}"

- name: GA | Web | Adding privileges
  ansible.builtin.template:
    src: 'templates/etc/sudoers.d/gaweb.j2'
    dest: '/etc/sudoers.d/gaweb'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
