---

- name: GA | Web | Installing packages
  ansible.builtin.apt:
    name: "{{ ga_web_packages }}"
    state: present

- name: GA | Web | Setting system timezone
  community.general.timezone:
    name: "{{ ga_timezone }}"

- name: GA | Web | Adding service group
  ansible.builtin.group:
    name: "{{ ga_service_group }}"
    state: present

- name: GA | Web | Adding service user
  ansible.builtin.user:
    name: "{{ ga_web_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "{{ ga_web_path_home }}"
    groups: "{{ ga_web_groups }}"
    append: yes
  ignore_errors: true
  register: ga_web_user_raw

- name: GA | Web | Adding service user to groups
  ansible.builtin.user:
    name: "{{ ga_web_service_user }}"
    groups: "{{ ga_web_groups }}"
    append: yes
  when:
    - ga_web_user_raw.failed is defined
    - ga_web_user_raw.failed

- name: GA | Web | Creating directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ga_web_service_user }}"
    group: "{{ ga_service_group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ ga_web_path }}", mode: '0755' }
    - { path: "{{ ga_web_path_static }}", mode: '0755' }
    - { path: "{{ ga_web_path_docs }}", mode: '0755' }
    - { path: "{{ ga_web_path_log }}", mode: '0775' }
    - { path: "{{ ga_web_path_venv }}", mode: '0750' }

- name: GA | Web | Copying web code
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/web/{{ ga_web_django_project }}/"
    dest: "{{ ga_web_path }}"
    recursive: yes
    rsync_path: 'sudo rsync'
    rsync_opts:
      - '--exclude=*.cnf'
      - '--exclude=*.conf'
      - '--exclude=static/'

- name: GA | Web | Copying web static-files
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/code/web/{{ ga_web_django_project }}/static/"
    dest: "{{ ga_web_path_static }}"
    recursive: yes
    rsync_path: 'sudo rsync'

- name: GA | Web | Copying docs
  ansible.posix.synchronize:
    src: "{{ ga_setup_clone_dir }}/docs/"
    dest: "{{ ga_web_path_docs }}"
    recursive: yes
    rsync_path: 'sudo rsync'

- name: GA | Web | Preparing docs building-script
  ansible.builtin.file:
    path: "{{ ga_web_path_docs }}/html.sh"
    mode: 0755

- name: GA | Web | Building docs html
  ansible.builtin.shell: './html.sh'
  args:
    executable: '/bin/bash'
    chdir: "{{ ga_web_path_docs }}"

- name: GA | Web | Setting privileges
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ ga_web_service_user }}"
    group: "{{ ga_service_group }}"
    recurse: true
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - {path: "{{ ga_web_path }}"}
    - {path: "{{ ga_web_path_static }}"}
    - {path: "{{ ga_web_path_docs }}", mode: '0755'}

- name: GA | Web | Configuring django settings
  ansible.builtin.lineinfile:
    path: "{{ ga_web_path }}/{{ ga_web_django_project }}/config.py"
    regexp: '{{ item.search }}'
    line: '{{ item.replace }}'
  loop: "{{ ga_django_config_replacement }}"

- name: GA | Web | Adding privileges
  ansible.builtin.template:
    src: 'templates/etc/sudoers.d/gaweb.j2'
    dest: '/etc/sudoers.d/gaweb'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
