---

ga_core_path_log: "{{ ga_path_log }}/core"

ga_core_raspiconfig:
  - 'nonint do_i2c 0'
  - 'nonint do_spi 0'

ga_settings:
  name: "{{ ga_core_controller_name }}"
  description: "Agent created by setup at {{ ansible_date_time.iso8601 }}"
  path_root: "{{ ga_core_path }}"
  path_home: "{{ ga_core_path_home }}"
  path_log: "{{ ga_path_log }}"
  sql_server: "{{ ga_sql_server }}"
  sql_port: "{{ ga_sql_port }}"
  sql_user: "{{ ga_sql_user_core }}"
  sql_database: "{{ ga_sql_db }}"
  sql_socket: "{{ ga_sql_socket }}"
  sql_service: "{{ ga_sql_service }}"
  sql_config: "{{ ga_sql_config_file }}"
  sql_secret: "{{ ga_sql_pwd_core }}"
  version: "{{ ga_setup_release }}"
  version_detail: "{{ ga_setup_commit }}"
  log_level: "{{ ga_log_level }}"
  security: "{% if ga_security_mode %}1{% else %}0{% endif %}"
  timezone: "{{ ga_timezone }}"
  device_log: "{% if ga_core_device_log %}1{% else %}0{% endif %}"
  device_fail_count: "{{ ga_shared_settings.device_fail_count }}"
  device_fail_sleep: "{{ ga_shared_settings.device_fail_sleep }}"
  debug: "{{ ga_shared_settings.debug }}"
  svc_interval_status: "{{ ga_shared_settings.svc_interval_status }}"
  svc_interval_reload: "{{ ga_shared_settings.svc_interval_reload }}"
  subprocess_timeout: "{{ ga_shared_settings.subprocess_timeout }}"
