project = 'GrowAutomation'
copyright = '2022, Superstes'
author = 'Superstes'
extensions = ['sphinx_rtd_theme']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_theme_options = {}
html_static_path = ['_static']
html_logo = '_static/img/ga02c.svg'
# html_favicon = '_static/img/favicon.ico'
html_css_files = ['css/ga.css']
master_doc = 'index'
display_version = True
# navigation_depth = 4
# collapse_navigation = True
sticky_navigation = True
