project = 'GrowAutomation'
copyright = '2021, Superstes'
author = 'René Pascal Rath'
extensions = ['sphinx_rtd_theme']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_theme_options = {}
html_static_path = ['_static']
html_logo = '_static/img/ga02c.svg'
navtree_shift = True
navtree_root_links = True
html_css_files = ['css/ga.css']
