---

# note: db-schema and initial controller configuration will be initialized by django

- name: GA | DB | Install mariadb
  ansible.builtin.apt:
    name: "{{ ga_db_packages }}"
    state: present
  notify: 'enable_mariadb'

- name: GA | DB | Creating database
  community.mysql.mysql_db:
    name: "{{ ga_sql_db }}"
    state: present
    login_unix_socket: "{{ ga_sql_socket }}"

- name: GA | DB | Creating users
  community.mysql.mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pwd }}"
    priv: "{{ ga_sql_db }}.*:ALL"
    state: present
    login_unix_socket: "{{ ga_sql_socket }}"
    host: "{{ ga_sql_user_host }}"
    update_password: on_create
  no_log: true
  ignore_errors: true  # if user already exist it will fail tue to a bug
  register: user_creation
  with_items:
    - {user: "{{ ga_sql_user_core }}", pwd: "{{ ga_sql_pwd_core }}"}
    - {user: "{{ ga_sql_user_web }}", pwd: "{{ ga_sql_pwd_web }}"}

- name: GA | DB | Displaying info
  ansible.builtin.debug:
    msg: "INFO: The creation of database users might fail if they already exist. In that case you can ignore this error!"
  when:
    - user_creation.failed is defined
    - user_creation.failed
