DATETIME_TS_FORMAT = '%Y-%m-%d %H:%M:%S'
CENSOR_SYMBOL = '●'
VERSION = 0.9
LOGIN_URL = '/accounts/login/'

# dashboard settings
MAX_DATA_POINTS_SHORT_CLI = 75
MAX_DATA_POINTS_MEDIUM_CLI = 250
MAX_DATA_POINTS_LONG_CLI = 500
MAX_DATA_POINTS_HUGE_CLI = 1500
MAX_DATA_POINTS_SHORT_MOBILE = 35
MAX_DATA_POINTS_MEDIUM_MOBILE = 100
MAX_DATA_POINTS_LONG_MOBILE = 250
MAX_DATA_POINTS_HUGE_MOBILE = 750
