---

- name: GA | Setup | Bootstrapping
  ansible.builtin.import_role:
    name: ansibleguy.linux_bootstrap
  vars:
    configure_firewall: false  # will be done explicitly
    configure_users: false
    configure_ssh: "{{ ga_ssh.configure }}"  # could be done as opt-in in the future (?)
    ssh_config:
      port: "{{ ga_ssh.port }}"
      allow_root: false
      auth_pwd: "{{ ga_ssh.auth_pwd }}"
      auth_pubkey: "{{ ga_ssh.auth_pubkey }}"
      msg: true
      welcome_msg:
        - '-----------------------------------------'
        - '| Welcome to this GrowAutomation server |'
        - '|    Your activities  will be logged    |'
        - '|           Keep on  growing!           |'
        - '-----------------------------------------'
    ansible_port: "{{ ga_ssh.port }}"

    configure_network: false
    configure_auto_update: true
    auto_update_config:
      time: 'Sun 00:00'
      auto_reboot: true
      auto_reboot_with_users: false
      auto_reboot_time: '02:00'
      exclusions: []
      exclude_kernel: false
      logging: true
      logging_verbose: true
  when: ga_bootstrap

# firewall management
- name: GA | Setup | GA Web/Core - Firewall
  ansible.builtin.import_role:
    name: ansibleguy.infra_ufw
  vars:
    ufw_rules:
      GrowAutomationWeb:
        port: "{{ ga_web_port_http }},{{ ga_web_port_https }}"
        proto: 'tcp'
      GrowAutomationCore:
        port: "{{ ga_core_port_socket }}"
        proto: 'tcp'
        log: true
  when:
    - ga_ufw_manage
    - ga_web_install
    - ga_core_install

- name: GA | Setup | GA Web - Firewall
  ansible.builtin.import_role:
    name: ansibleguy.infra_ufw
  vars:
    ufw_rules:
      GrowAutomationWeb:
        port: "{{ ga_web_port_http }},{{ ga_web_port_https }}"
        proto: 'tcp'
  when:
    - ga_ufw_manage
    - ga_web_install
    - not ga_core_install

- name: GA | Setup | GA Core - Firewall
  ansible.builtin.import_role:
    name: ansibleguy.infra_ufw
  vars:
    ufw_rules:
      GrowAutomationCore:
        port: "{{ ga_core_port_socket }}"
        proto: 'tcp'
        log: true
  when:
    - ga_ufw_manage
    - ga_core_install
    - not ga_web_install
