---

- debug:
    msg:
      - '########################################'
      - '########################################'
      - '######### Preparing for Update #########'
      - '########################################'
      - '########################################'

- name: GA | Update | Installing dependencies
  ansible.builtin.apt:
    name: "{{ ga_update_packages }}"

- name: GA | Update | Preparing
  ansible.builtin.import_tasks: preparations.yml

- name: GA | Update | Running pre-checks
  ansible.builtin.import_tasks: checks.yml

- name: GA | Update | Backing-up current version
  ansible.builtin.import_tasks: backup.yml

- debug:
    msg:
      - '########################################'
      - '########################################'
      - "GrowAutomation will now be upgraded to version {{ ga_update_release_now }} - {{ ga_update_commit_now }}"
      - '########################################'
      - '########################################'

- name: GA | Update | Running update tasks
  ansible.builtin.import_tasks: do.yml

# todo: update version in db
# todo: what if db schema changed too much? => maybe allow user to pass a 'migrate-db' flag (or something like that)
#   if that flag is set we will:
#   1. export the db data without 'if table does not exist' statements
#   2. drop the db
#   3. remove all migrations
#   4. create the new db schema
#   5. try to import the data and config as good as possible (data should never be a problem => config could be)

- name: GA | Update | Evaluating update result
  ansible.builtin.set_fact:
    ga_update_failed: true
  changed_when: false
  when: >
    (update_remove_venv.failed is defined and update_remove_venv.failed) or
    (update_venv.failed is defined and update_venv.failed) or
    (update_code.failed is defined and update_code.failed) or
    (update_code_privs.failed is defined and update_code_privs.failed) or
    (update_code_privs_secret.failed is defined and update_code_privs_secret.failed) or
    (update_db_schema_build.failed is defined and update_db_schema_build.failed) or
    (update_db_schema_migrate.failed is defined and update_db_schema_migrate.failed) or
    (update_apt is defined and update_apt.failed is defined and update_apt.failed) or
    (update_start_svc is defined and update_start_svc.failed is defined and update_start_svc.failed)

- name: GA | Update | Trying to restore old version if update failed
  ansible.builtin.import_tasks: restore.yml
  when: ga_update_failed

- name: GA | Update | Updating version number
  ansible.builtin.shell: "echo \"{{ item }};\" | mysql --defaults-file={{ ga_update_path_web }}/{{ ga_db_config }} {{ ga_sql_db }}"
  with_items:
    - "update ga_systemagentmodel set version='{{ ga_update_release_now }}', version_detail='{{ ga_update_commit_now }}'"  # todo: once there is support for multiple agents we will need to target the update-cmd
    - "update ga_systemservermodel set version='{{ ga_update_release_now }}', version_detail='{{ ga_update_commit_now }}'"
  when: not ga_update_failed

- name: GA | Update | Restarting services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - 'ga_core.service'
    - 'apache2.service'

- debug:
    msg:
      - '########################################'
      - '########################################'
      - "GrowAutomation was successfully updated to version {{ ga_update_release_now }} - {{ ga_update_commit_now }}"
      - '########################################'
      - '########################################'
  when: not ga_update_failed

- debug:
    msg:
      - '########################################'
      - '########################################'
      - "GrowAutomation update to version {{ ga_update_release_now }} - {{ ga_update_commit_now }} FAILED"
      - '########################################'
      - '########################################'
  when: ga_update_failed
