---

- name: GA | Update | Restore | Saving logs for debug reasons
  ansible.builtin.shell: "tar cf - {{ ga_update_path_log }} | xz -7 > {{ ga_update_path_backup }}/log_restore.tar.xz"
  warn: false

- name: GA | Update | Restore | Stopping core service
  ansible.builtin.systemd:
    name: 'ga_core.service'
    state: stopped

- name: GA | Update | Restore | Removing directories
  ansible.builtin.file:
    path: "{{ ga_update_path_backup }}"
    force: yes
    state: absent
  with_items:
    - "{{ ga_update_path_core }}"
    - "{{ ga_update_path_web }}"
    - "{{ ga_update_path_web_static }}"
    - "{{ ga_update_path_home_core }}"
    - "{{ ga_update_path_home_web }}"
    - "{{ ga_update_path_log }}"

- name: GA | Update | Restore | Restoring directories
  ansible.builtin.shell: "tar -xJf {{ item }} -C /"
  warn: false
  with_items:
    - "{{ ga_update_path_backup }}/core.tar.xz"
    - "{{ ga_update_path_backup }}/web.tar.xz"
    - "{{ ga_update_path_backup }}/web_static.tar.xz"
    - "{{ ga_update_path_backup }}/home_core.tar.xz"
    - "{{ ga_update_path_backup }}/home_web.tar.xz"
    - "{{ ga_update_path_backup }}/log.tar.xz"

- name: GA | Update | Restore | Restoring database
  ansible.builtin.shell: "xzcat {{ ga_update_path_backup }}/db.sql.xz |
  mysql --defaults-file={{ ga_update_path_web }}/{{ ga_db_config }} --single-transaction --force {{ ga_sql_db }}"

- name: GA | Update | Restore | Starting core service
  ansible.builtin.systemd:
    name: 'ga_core.service'
    state: started
