---

ga_ssl_path_ca: "/etc/ssl/certs/ga.ca.pem"  # needed if self-signed
ga_ssl_path_key: "/etc/ssl/private/{{ ga_web_dns }}.pem"
ga_ssl_path_cert: "/etc/ssl/certs/{{ ga_web_dns }}.pem"
ga_ssl_path_fullchain: "/etc/ssl/certs/{{ ga_web_dns }}.fullchain.pem"

ga_web_path_log: "{{ ga_path_log }}/web"
ga_web_key: "{{ ga_web_dns | replace('.', '_') }}"
ga_web_autoindex: false

ga_apache_config_additions:
  ServerTokens: 'Prod'
  ServerSignature: 'Off'

ga_apache_envvar_replacement:
  - {search: '^export APACHE_RUN_USER',
     replace: "export APACHE_RUN_USER={{ ga_web_service_user }}"}
  - {search: '^export APACHE_RUN_GROUP',
     replace: "export APACHE_RUN_GROUP={{ ga_web_service_user }}"}

ga_django_config_replacement:
  - {search: '^DEBUG = True$',
     replace: 'DEBUG = False'}
  - {search: '^ALLOWED_HOSTS = ',
     replace: "ALLOWED_HOSTS = [own_ip, 'localhost', '{{ ga_web_dns }}'{% for alias in ga_web_alias %}, '{{ alias }}' {% endfor %}]"}
  - {search: "^SECRET_KEY = 'REPLACE-WITH-PRODUCTION-KEY'$",
     replace: "SECRET_KEY = '{{ lookup('password', '/dev/null chars=ascii_letters,digits length=50') }}'"}
  - {search: "^TIME_ZONE = 'Europe\/Vienna'$",
     replace: "TIME_ZONE = '{{ ga_timezone }}'"}

ga_django_groups:
  - 'ga_read'
  - 'ga_user'
  - 'ga_write'
  - 'ga_admin'

ga_settings:
  server:
    name: "'{{ ga_core_controller_name }}'"
    description: "'Server created by setup at {{ ansible_date_time.iso8601 }}'"
    path_core: "'{{ ga_core_path }}'"
    path_web: "'{{ ga_web_path }}'"
    path_web_static: "'{{ ga_web_path_static }}'"
    path_web_docs: "'{{ ga_web_path_docs }}'"
    path_home_core: "'{{ ga_core_path_home }}'"
    path_home_web: "'{{ ga_web_path_home }}'"
    path_log: "'{{ ga_path_log }}'"
    sql_server: "'{{ ga_sql_server }}'"
    sql_port: "{{ ga_sql_port }}"
    sql_user: "'{{ ga_sql_user_web }}'"
    sql_database: "'{{ ga_sql_db }}'"
    sql_service: "'{{ ga_sql_service }}'"
    # sql_secret: "'{{ ga_sql_pwd_web }}'"  # to be encrypted
    log_level: "{{ ga_log_level }}"
    security: "{% if ga_security_mode %}1{% else %}0{% endif %}"
    timezone: "'{{ ga_timezone }}'"
    version: "'{{ ga_setup_release }}'"
    version_detail: "'{{ ga_setup_commit }}'"
    letsencrypt: "{% if ga_web_ssl_mode == 'letsencrypt' %}1{% else %}0{% endif %}"

  agent:
    name: "'{{ ga_core_controller_name }}'"
    description: "'Agent created by setup at {{ ansible_date_time.iso8601 }}'"
    path_root: "'{{ ga_core_path }}'"
    path_home: "'{{ ga_core_path_home }}'"
    path_log: "'{{ ga_path_log }}'"
    sql_server: "'{{ ga_sql_server }}'"
    sql_port: "{{ ga_sql_port }}"
    sql_user: "'{{ ga_sql_user_core }}'"
    sql_database: "'{{ ga_sql_db }}'"
    sql_socket: "'{{ ga_sql_socket }}'"
    sql_service: "'{{ ga_sql_service }}'"
    sql_config: "'{{ ga_sql_config_file }}'"
    # sql_secret: "'{{ ga_sql_pwd_core }}'"  # to be encrypted
    version: "'{{ ga_setup_release }}'"
    version_detail: "'{{ ga_setup_commit }}'"
    log_level: "{{ ga_log_level }}"
    device_fail_count: "{{ ga_shared_settings.device_fail_count }}"
    device_fail_sleep: "{{ ga_shared_settings.device_fail_sleep }}"
    debug: "{{ ga_shared_settings.debug }}"
    svc_interval_status: "{{ ga_shared_settings.svc_interval_status }}"
    svc_interval_reload: "{{ ga_shared_settings.svc_interval_reload }}"
    subprocess_timeout: "{{ ga_shared_settings.subprocess_timeout }}"
