---

ga_ssl_path_ca: "/etc/ssl/certs/ga.ca.pem"  # needed if self-signed
ga_ssl_path_key: "/etc/ssl/private/{{ ga_web_dns }}.pem"
ga_ssl_path_cert: "/etc/ssl/certs/{{ ga_web_dns }}.pem"
ga_ssl_path_fullchain: "/etc/ssl/certs/{{ ga_web_dns }}.fullchain.pem"

ga_web_path_log: "{{ ga_path_log }}/web"
ga_web_key: "{{ ga_web_dns | replace('.', '_') }}"
ga_web_port_http: 80
ga_web_port_https: 443
ga_web_autoindex: false

ga_apache_config_additions:
  ServerTokens: 'Prod'
  ServerSignature: 'Off'

ga_apache_envvar_replacement:
  - { search: '^export APACHE_RUN_USER',
      replace: "export APACHE_RUN_USER={{ ga_web_service_user }}" }
  - { search: '^export APACHE_RUN_GROUP',
      replace: "export APACHE_RUN_GROUP={{ ga_web_service_user }}" }

ga_django_config_replacement:
  - {search: '^DEBUG = True$',
     replace: 'DEBUG = False'}
  - {search: '^ALLOWED_HOSTS = ',
     replace: "ALLOWED_HOSTS = [own_ip, 'localhost', '{{ ga_web_dns }}'{% for alias in ga_web_alias %}, '{{ alias }}' {% endfor %}]"}
  - {search: "^SECRET_KEY = 'REPLACE-WITH-PRODUCTION-KEY'$",
     replace: "SECRET_KEY = '{{ lookup('password', '/dev/null chars=ascii_letters,digits length=50') }}'"}
  - {search: "^TIME_ZONE = 'Europe\/Vienna'$",
     replace: "TIME_ZONE = '{{ ga_timezone }}'"}

ga_django_groups:
  - 'ga_read'
  - 'ga_user'
  - 'ga_write'
